name: Docker Image Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: app
        # List of metadata for an image
        labels: ${{ github.ref_name}},$(get rev-parse --short HEAD),latest
        # List of target platforms for build
        platforms: linux/amd64,linux/arm64
        # List of tags
        tags: dgarciabriseno/hv-coordinator
          
